name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    name: Build and Release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
            arch: x64
          - os: windows-latest
            rust_target: aarch64-pc-windows-msvc
            arch: arm64
          - os: ubuntu-22.04
            rust_target: x86_64-unknown-linux-gnu
            arch: x64
          - os: ubuntu-22.04
            rust_target: aarch64-unknown-linux-gnu
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.rust_target }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Install cross-compilation tools for Linux ARM64
        if: matrix.rust_target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install frontend dependencies
        run: npm install

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: ${{ matrix.rust_target == 'aarch64-unknown-linux-gnu' && 'aarch64-linux-gnu-gcc' || '' }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "ACGStation Sync v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          args: --target ${{ matrix.rust_target }}
